stages:
  - test
  - pages

build-fedora-28-openjdk-11:
  image: fedora:28
  stage: test
  dependencies: []
  before_script:
    - dnf install -y -q java-11-openjdk-devel gradle inkscape ocaml-csv
    - export JAVA_HOME="$(echo /usr/lib/jvm/java-11-openjdk-*)" && echo $JAVA_HOME
    - export PATH="$JAVA_HOME/bin:$PATH" && echo $PATH
    - which java; java -version; which javac; javac --version; echo "$JAVA_HOME"
  script:
    - ./gradlew --version
    - ./gradlew assemble
    - ./gradlew check
    - ./gradlew build -i
    - ./gradlew executableJar
    - ./bin/generateHelpDocs.sh
    - ./bin/travis_ci_after_build_checks.sh
  artifacts:
    paths:
      - library/build/docs/javadoc
      - tool/build/docs/javadoc
      - 'docs/src/*/*.help.txt'
      - 'docs/src/*/*/*.help.txt'

pages-test:
  # https://hub.docker.com/_/rust/
  image: "kravemir/mdbook:0.2.1"
  stage: pages
  before_script:
    - apt-get update -qq && apt-get install -y -qq openjdk-8-jdk gradle make inkscape
  script:
    - mkdir public-tmp
    - ./bin/copyJavadocToBook.sh
    - mdbook build docs
  except:
  - released

pages:
  # https://hub.docker.com/_/rust/
  image: "kravemir/mdbook:0.2.1"
  stage: pages
  before_script:
    - apt-get update -qq && apt-get install -y -qq openjdk-8-jdk gradle make inkscape
  script:
    - mkdir public-tmp
    - ./bin/copyJavadocToBook.sh
    - mdbook build docs
    - cp -r docs/book/* public-tmp
    - mv public-tmp public
    - find $PWD/public
  artifacts:
    paths:
      - public
  only:
  - released
