stages:
  - test
  - pages

build-test-go:
  image: golang:1.19.3-alpine3.16
  stage: test
  dependencies: []
  before_script:
    - apk add build-base bash
  script:
    - go build ./...
    - go test ./...
    - gofmt -w .
    - go build -o ./labelset -v .
    - ./bin/generateHelpDocs.sh
    - ./bin/travis_ci_after_build_checks.sh
  artifacts:
    paths:
      - 'docs/src/*/*.help.txt'
      - 'docs/src/*/*/*.help.txt'
