baseURL = "http://localhost"
title = "labelset"
theme = "hugo-book"

disableKinds = ['taxonomy', 'taxonomyTerm']

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
style = 'tango'

[params]
  BookTheme = 'auto'
  BookSearch = false
  BookSection = '*'
  BookRepo = 'https://github.com/kravemir/labelset'


[menu]

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/kravemir/labelset"
  weight = 10

