name: lablie
version: UNDEFINED
version-script: sed -n '/^version=/{s///; s/\r$//; p; q}' gradle.properties
summary: SVG print labels generator
description: |
  Designed to be simply usable java tool for generation of documents with
  labels for printing. Supports combining of multiple labels and instancing
  within single document.

confinement: strict

apps:
  lablie:
    command: lablie/lablie-tool.sh
    plugs: [home]

parts:
  lablie:
    plugin: gradle
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      ./gradlew :lablie-tool:executableJar
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/lablie
      cp tool/build/libs/lablie-tool-*-executable.jar -d $SNAPCRAFT_PART_INSTALL/lablie/lablie-tool.jar
      echo java -jar "\$SNAP/lablie/lablie-tool.jar" '"$@"' > $SNAPCRAFT_PART_INSTALL/lablie/lablie-tool.sh
      chmod 755 $SNAPCRAFT_PART_INSTALL/lablie/lablie-tool.sh
    build-packages:
      - unzip
      - openjdk-8-jdk
