# This workflow will publish a docker image
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub and GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            kravemir/labelset
            ghcr.io/${{ github.repository }}

      - name: Prepare metadata (extra-fonts flavor)
        id: meta-extra-fonts
        uses: docker/metadata-action@v4
        with:
          images: |
            kravemir/labelset
            ghcr.io/${{ github.repository }}
          flavor: |
            suffix=-extra-fonts

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base

# TODO: build conditionally on releases only, this is crazy big
#      - name: Build and push images (extra-fonts flavor)
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta-extra-fonts.outputs.tags }}
#          labels: ${{ steps.meta-extra-fonts.outputs.labels }}
#          target: 'extra-fonts'
