# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build executable
        run: go build -o labelset -v .

      - run: gofmt -w .

      - name: Generate Markdown Pages for CLI
        run: ./bin/generate_cli_markdown_pages.sh

      - name: Custom checks after build
        run: ./bin/after_build_checks.sh
